// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package admindb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TacokumoAdminAccount struct {
	ID        int64
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TacokumoAdminAccountIdentity struct {
	ID            int64
	AccountID     int64
	EmailVerified bool
	Issuer        string
	Sub           string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TacokumoAdminProject struct {
	ID        int64
	Name      pgtype.Text
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TacokumoAdminProjectAccountRelationship struct {
	ID        int64
	ProjectID int64
	AccountID int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
