// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package admindb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAccountExists = `-- name: CheckAccountExists :one
SELECT EXISTS (
  SELECT 1
  FROM tacokumo_admin.accounts
  WHERE email = $1
)
`

// CheckAccountExists
//
//	SELECT EXISTS (
//	  SELECT 1
//	  FROM tacokumo_admin.accounts
//	  WHERE email = $1
//	)
func (q *Queries) CheckAccountExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkDBConnection = `-- name: CheckDBConnection :one
SELECT 1
`

// CheckDBConnection
//
//	SELECT 1
func (q *Queries) CheckDBConnection(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkDBConnection)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO tacokumo_admin.projects (name, bio) VALUES ($1, $2)
`

type CreateProjectParams struct {
	Name pgtype.Text
	Bio  pgtype.Text
}

// CreateProject
//
//	INSERT INTO tacokumo_admin.projects (name, bio) VALUES ($1, $2)
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.Name, arg.Bio)
	return err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, bio, created_at, updated_at
FROM tacokumo_admin.projects
WHERE name = $1
`

// GetProjectByName
//
//	SELECT id, name, bio, created_at, updated_at
//	FROM tacokumo_admin.projects
//	WHERE name = $1
func (q *Queries) GetProjectByName(ctx context.Context, name pgtype.Text) (TacokumoAdminProject, error) {
	row := q.db.QueryRow(ctx, getProjectByName, name)
	var i TacokumoAdminProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsWithPagination = `-- name: ListProjectsWithPagination :many
SELECT id, name, bio, created_at, updated_at
FROM tacokumo_admin.projects
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProjectsWithPaginationParams struct {
	Limit  int32
	Offset int32
}

// ListProjectsWithPagination
//
//	SELECT id, name, bio, created_at, updated_at
//	FROM tacokumo_admin.projects
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListProjectsWithPagination(ctx context.Context, arg ListProjectsWithPaginationParams) ([]TacokumoAdminProject, error) {
	rows, err := q.db.Query(ctx, listProjectsWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TacokumoAdminProject
	for rows.Next() {
		var i TacokumoAdminProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
