// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package admindb

import (
	"context"
)

const checkDBConnection = `-- name: CheckDBConnection :one
SELECT 1
`

// CheckDBConnection
//
//	SELECT 1
func (q *Queries) CheckDBConnection(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkDBConnection)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO tacokumo_admin.projects (name, description, kind) VALUES ($1, $2, $3)
`

type CreateProjectParams struct {
	Name        string
	Description string
	Kind        string
}

// CreateProject
//
//	INSERT INTO tacokumo_admin.projects (name, description, kind) VALUES ($1, $2, $3)
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.Exec(ctx, createProject, arg.Name, arg.Description, arg.Kind)
	return err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, description, kind, created_at, updated_at
FROM tacokumo_admin.projects
WHERE name = $1
`

// GetProjectByName
//
//	SELECT id, name, description, kind, created_at, updated_at
//	FROM tacokumo_admin.projects
//	WHERE name = $1
func (q *Queries) GetProjectByName(ctx context.Context, name string) (TacokumoAdminProject, error) {
	row := q.db.QueryRow(ctx, getProjectByName, name)
	var i TacokumoAdminProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsWithPagination = `-- name: ListProjectsWithPagination :many
SELECT id, name, description, kind, created_at, updated_at
FROM tacokumo_admin.projects
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProjectsWithPaginationParams struct {
	Limit  int32
	Offset int32
}

// ListProjectsWithPagination
//
//	SELECT id, name, description, kind, created_at, updated_at
//	FROM tacokumo_admin.projects
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListProjectsWithPagination(ctx context.Context, arg ListProjectsWithPaginationParams) ([]TacokumoAdminProject, error) {
	rows, err := q.db.Query(ctx, listProjectsWithPagination, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TacokumoAdminProject
	for rows.Next() {
		var i TacokumoAdminProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
